kind: pipeline
type: docker
name: 4d-shop
steps:
- name: build-shop
  image: node:12.9.1-alpine
  commands:
  - npm install
  - npm run build
- name: publish-shop
  image: plugins/docker
  when:
    branch: master
    event: push
  settings:
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
    repo: 4ding/shop-client
    cache_from: 4ding/shop-client
    tags:
    - 'latest'
    - '0.0.0'
    dockerfile: drone-ci/Dockerfile
    environment:
      SERVER_HOST: https://shop.4ding.site
    build_args_from_env:
    - SERVER_HOST