kind: pipeline
type: docker
name: 4d-shop
steps:
# - name: build-shop
#   image: node:12.9.1-alpine
#   commands:
#   - npm install
#   - npm run build
- name: publish-shop
  image: plugins/docker
  when:
    branch: master
    event: push
  settings:
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
    repo: 4ding/shop-client
    cache_from: 4ding/shop-client
    tags:
    - 'latest'
    - '0.0.0'
    dockerfile: drone-ci/Dockerfile
- name: git-clone-charts
  image: alpine/git
  environment:
    GIT_USERNAME:
      from_secret: git_username
    GIT_PASSWORD:
      from_secret: git_password
  commands:
  - git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/4ding-cpp/charts.git
- name: helm-upgrade
  image: pelotech/drone-helm3
  environment:
    KUBE_API_SERVER:
      from_secret: kube_api_server
    KUBE_TOKEN:
      from_secret: kube_token
    KUBE_CERTIFICATE:
      from_secret: kube_ca
  settings:
    mode: upgrade
    chart: ./charts/business
    namespace: test
    release: business