---
# Source: business/templates/containers.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - env:
        - name: BUSINESS
          value: "test"
        - name: "BUILD_NUMBER"
          value: "{{build_number}}"
        image: 4ding/shop-client:latest
        name: web1
        volumeMounts:
        - mountPath: /assets
          name: nfs-230
      volumes:
      - name: nfs-230
        nfs:
          path: /usr/nfs/test
          server: 192.168.69.230